spring:
  application:
    name: springbootthymeleafwithhtmlx
  threads:
    virtual:
      enabled: true
  mvc:
    #ข้อควรระวัง: ถ้าวันหลังตั้งชื่อ path ของ controller ซ้ำกับโฟลเดอร์ static เช่น /webui/css/... controller จะบังไฟล์นั้น
    static-path-pattern: /webui/**
server:
  forward-headers-strategy: native
